version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/lostandfound
    depends_on:
      - mongo

volumes:
  mongo-data: